//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace cn.sharesdk.unity3d
{
	/// <summary>
	/// Platform type.
	/// </summary>
	public enum PlatformType
	{
		Unknown = 0,
		QZone = 6, 				//QZone           
		
		WeChat = 22,		    //WeChat Friends    
		WeChatMoments = 23,	    //WeChat WechatMoments   
		QQ = 24,				//QQ              
		
        #if UNITY_ANDROID
		WechatPlatform = 22,  
		QQPlatform = 24,
		#elif UNITY_IPHONE	
		YixinPlatform = 994,    //Yixin series
		KakaoPlatform = 995,    //Kakao series
		EvernoteInternational = 996,//Evernote InternationaL Edition
		WechatPlatform = 997,   //Wechat Series
		QQPlatform = 998,		//QQ Series  
		#endif

	}

}

