using System;

namespace Engine
{
    enum MessageTypeBase
    {
        MSG_BASE_ID = 0x00400000,

        /**
         * Login game
         * */
        MSG_C2FD_QUERY_FEP_ID = MSG_BASE_ID + 0x0008,
        MSG_FD2C_QUERY_FEP_ID = MSG_BASE_ID + 0x0009,
        MSG_C2F_LOGIN_ID = MSG_BASE_ID + 0x0101,
        MSG_D2F2C_LOGIN_ID = MSG_BASE_ID + 0x0102,
		MSG_C2F_PING_ID = MSG_BASE_ID + 0x10401,

		MSG_W2F2B_DISCONNECT_CLIENT = MSG_BASE_ID + 0x10302,

        /**
         * Select Character
         * */
        MSG_C2F2D_SELECT_CHARACTER = MSG_BASE_ID + 0x0203,
        MSG_D2F2C_SELECT_CHARACTER = MSG_BASE_ID + 0x0204,

		MSG_C2F2D_EXIT_CHARACTER = MSG_BASE_ID + 0x0207,
		
		/**
		 * Create Character
		 * */
		MSG_C2F2D_CREATE_CHARACTER = MSG_BASE_ID + 0x0201,
		MSG_D2F2C_CREATE_CHARACTER = MSG_BASE_ID + 0x0202,
		
		/**
		 * Delete Character
		 * */
		MSG_C2F2D_DELETE_CHARACTER = MSG_BASE_ID + 0x0205, 
		MSG_D2F2C_DELETE_CHARACTER = MSG_BASE_ID + 0x0206,

		MSG_W2F2C_WORLD_RESOURCE_LOAD_COMPLETE = MSG_BASE_ID + 0x14004,
		
		/**
		 * entry space message
		 * */
		MSG_C2F2B_ENTERSPACE = MSG_BASE_ID + 0x0304,
		MSG_B2F2C_ENTERSPACE = MSG_BASE_ID + 0x0305,
		MSG_C2F2B_LEFTSPACE  = MSG_BASE_ID + 0x0312,
		MSG_B2F2C_ACK_ALL_DATA_RECV_COMPLETED = MSG_BASE_ID + 0x38016,

		MSG_D2F2C_PUSH_PREPAY_INFO = MSG_BASE_ID + 0x2606A,//充值.
		MSG_W2F2C_PUSH_CHAR_MANAGER = MSG_BASE_ID + 0x2A319,//封号禁言等.
		
		/**
		 * select instance
		 * */
		MSG_C2F2B_GOTO_INSTANCE = MSG_BASE_ID + 0x0609,
		
		MSG_C2F2D_REQ_EQUIPMENT_BAG = MSG_BASE_ID + 0x26001,//装备.
		MSG_D2F2C_ACK_EQUIPMENT_BAG = MSG_BASE_ID + 0x36001,
        
		MSG_C2F2D_REQ_MATERIAL_BAG = MSG_BASE_ID + 0x2600D,//材料.
		MSG_D2F2C_ACK_MATERIAL_BAG = MSG_BASE_ID + 0x3600D,//材料.
		
		MSG_C2F2D_REQ_STRENGTHENING_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID + 0x2600F ,//请求玩家已经强化信息Free模式.
		MSG_D2F2C_ACK_STRENGTHENING_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID + 0x3600F ,
		
		MSG_C2F2D_REQ_EQU_SPEC_ATTRI = MSG_BASE_ID+0x2600E, //请求装备附带的特殊属性.
		MSG_D2F2C_ACK_EQU_SPEC_ATTRI = MSG_BASE_ID+0x3600E,
		
		/*MSG_C2F2D_REQ_STRENGTHENING_EQUIPMENT_BY_INGOT = MSG_BASE_ID + 0x26010,//请求玩家已经强化信息收费模式.
		MSG_D2F2C_ACK_STRENGTHENING_EQUIPMENT_BY_INGOT = MSG_BASE_ID + 0x36010,*/
		
		MSG_C2F2D_REQ_UPSTAR_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID+0x26011, //请求升星Free模式.
		MSG_D2F2C_ACK_UPSTAR_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID+0x36011,
		
		MSG_C2F2D_REQ_UPSTAR_EQUIPMENT_BY_INGOT = MSG_BASE_ID+0x26012,//请求升星收费模式.
		MSG_D2F2C_ACK_UPSTAR_EQUIPMENT_BY_INGOT = MSG_BASE_ID+0x36012,
		
		MSG_C2F2D_EQU_EQUIPMENT =  MSG_BASE_ID + 0x26035,//换装备
        MSG_D2F2C_EQU_EQUIPMENT = MSG_BASE_ID + 0x36035,
		
        MSG_C2F2D_REQ_GET_CHEST_AWARD_FOR_FIRST_PASS_DUP = MSG_BASE_ID + 0x26048,//通关领取宝箱（UI界面内）.
        MSG_D2F2C_ACK_GET_CHEST_AWARD_FOR_FIRST_PASS_DUP = MSG_BASE_ID + 0x36048,

		MSG_C2F2D_REQ_QUERY_CHEST_AWARD_INFO_FOR_FIRST_PASS_DUP = MSG_BASE_ID + 0x26047,//通关领取宝箱的所有信息（UI界面内）.
        MSG_D2F2C_ACK_QUERY_CHEST_AWARD_INFO_FOR_FIRST_PASS_DUP = MSG_BASE_ID + 0x36047,

		MSG_C2F2D_REQ_RESOLVE_EQUIPMENT = MSG_BASE_ID+0x26013,//分解.
		MSG_D2F2C_ACK_RESOLVE_EQUIPMENT = MSG_BASE_ID+0x36013,
		
        MSG_C2F2D_REQ_RESOLVE_A_LOT_OF_EQUIPMENT = MSG_BASE_ID + 0x2603C,//一键分解.
        MSG_D2F2C_ACK_RESOLVE_A_LOT_OF_EQUIPMENT = MSG_BASE_ID + 0x3603C,

		MSG_C2F2D_REQ_OPEN_STRENGHTHEN_UI= MSG_BASE_ID + 0x26010,//开始强化.

		//客户端请求积分排行第一公会的ID
		MSG_C2F2W_REQ_SOCIATY_SCORE_RANK_TOP = MSG_BASE_ID + 0x2A332,
		MSG_W2F2C_ACK_SOCIATY_SCORE_RANK_TOP = MSG_BASE_ID + 0x3A332,

		MSG_C2F2B_REQ_ENTER_ELITE_COPY = MSG_BASE_ID + 0x28158,//客户端请求进入精英副本.
		MSG_B2F2C_ACK_ENTER_ELITE_COPY = MSG_BASE_ID + 0x38158,
		MSG_C2F2B_REQ_LEVEA_SINGLE_DUPLICATE_ELITE = MSG_BASE_ID + 0x28160,//玩家离开单人副本.

		MSG_C2F2B_REQ_ELITE_DUPLICATE_INFO = MSG_BASE_ID + 0x2815A,//客户端请求精英副本内的数据, 包括木桶掉落, BOSS 掉落, 宝箱掉落 等等.
		MSG_B2F2C_ACK_CASK_INFO_ELITE = MSG_BASE_ID + 0x3815A,//木桶掉落的铜币.
		MSG_B2F2C_ACK_BOTTLES_INFO_ELITE = MSG_BASE_ID + 0x3815B,//下发红蓝瓶信息.
		MSG_B2F2C_ACK_ELITE_DROP_ITEM_ELITE = MSG_BASE_ID + 0x3815C,//下发精英怪物的掉落物品.
		MSG_B2F2C_ACK_CHEST_DROP_ITEM_ELITE = MSG_BASE_ID + 0x3815D,//下发宝箱的掉落物品.
		MSG_B2F2C_ACK_ALL_MONSTER_EXP_ELITE = MSG_BASE_ID + 0x3815E,//下发各个怪物的经验集合.
		MSG_B2F2C_CONSUME_FOR_RELIVE_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x3815F,//下发副本中复活所需要的花费.
		MSG_B2F2C_ACK_ELITE_AWARD_PRESTIGE = MSG_BASE_ID + 0x3816C,

		MSG_C2F2B_REQ_PICKED_UP_COPPER_ELITE = MSG_BASE_ID + 0x28161,//客户端拾取铜币.
		MSG_C2F2B_REQ_PICKED_UP_EQUIPMENT_ELITE = MSG_BASE_ID + 0x28162,

		MSG_C2F2B_REQ_ADD_EXP_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28166,

		MSG_C2F2B_REQ_KILLED_BOSS_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28164,
		MSG_B2F2C_ACK_KILLED_BOSS_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x38165,

		MSG_C2F2B_REQ_KILL_ALL_MONSTER_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28167,
		MSG_B2F2C_ACK_KILL_ALL_MONSTER_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x38167,

		MSG_C2F2B_REQ_RELIVE_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28163,
		MSG_B2F2C_ACK_RELIVE_IN_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x38163,

		MSG_C2F2B_REQ_QUERY_PAY_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28168,
		MSG_B2F2C_ACK_QUERY_PAY_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x38168,
		MSG_C2F2B_REQ_GET_PAY_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x28169,

		MSG_C2F2B_REQ_QUERY_FREE_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x2816A,
		MSG_B2F2C_ACK_QUERY_FREE_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x3816A,
		MSG_C2F2B_REQ_GET_FREE_PRIZES_SINGLE_DUP_ELITE = MSG_BASE_ID + 0x2816B,

		MSG_C2F2B_REQ_EXIT_ELITE = MSG_BASE_ID + 0x28170,//玩家主动退出精英副本协议.
		MSG_C2F2B_REQ_EXIT_FAM = MSG_BASE_ID + 0x28171,//玩家主动退出秘境协议.

		MSG_C2F2B_ENTER_SINGLE_DUPLICATE = MSG_BASE_ID + 0x28001,//进入副本.
		MSG_B2C_ACK_ENTER_SINGLE_DUPLICATE = MSG_BASE_ID + 0x38001,//返回进入副本.
		MSG_C2F2B_REQ_LEVEA_SINGLE_DUPLICATE = MSG_BASE_ID + 0x28006,//离开副本.
		
		MSG_C2F2B_REQ_SINGLE_DUPLICATE_INFO = MSG_BASE_ID + 0x28005,//客户端请求副本内的数据, 包括木桶掉落, BOSS掉落, 宝箱掉落等等.
		MSG_B2F2C_ACK_CASK_INFO = MSG_BASE_ID + 0x38005,//每个木桶铜币的数量.
		MSG_B2F2C_ACK_BOTTLES_INFO = MSG_BASE_ID + 0x38007,//普通怪物掉落的血瓶和蓝瓶.
		MSG_B2F2C_ACK_ELITE_DROP_ITEM = MSG_BASE_ID + 0x38008,//精英怪掉落的物品.
		MSG_B2F2C_ACK_CHEST_DROP_ITEM = MSG_BASE_ID + 0x38009,//宝箱掉落的物品.
		MSG_B2F2C_ACK_ALL_MONSTER_EXP = MSG_BASE_ID + 0x3800A,//副本中的怪物总经验, 【不包含炮塔经验】, 【不包含过关奖励的经验】.
		MSG_B2F2C_CONSUME_FOR_RELIVE_IN_SINGLE_DUP = MSG_BASE_ID + 0x3801A,//下发副本中复活所需要的花费.
		MSG_B2F2C_FIRST_PASS_SINGLE_DUP = MSG_BASE_ID + 0x3801B,
		
		MSG_C2F2B_REQ_PICKED_UP_COPPER = MSG_BASE_ID + 0x2800B,//客户端拾取铜币.
		MSG_C2F2B_REQ_PICKED_UP_EQUIPMENT = MSG_BASE_ID + 0x2800C,//客户端在单人剧情副本中( 普通难度 )拾取装备.
		
		MSG_C2F2B_REQ_ADD_EXP_IN_SINGLE_DUP = MSG_BASE_ID + 0x2800F,//每次杀死怪物或者摧毁炮塔, 把获得的经验告诉服务端.
		
		MSG_C2F2B_REQ_KILLED_BOSS_IN_SINGLE_DUP = MSG_BASE_ID + 0x2800E,//客户端通知服务端杀掉BOSS了.
		MSG_B2F2C_ACK_KILLED_BOSS_IN_SINGLE_DUP = MSG_BASE_ID + 0x3800E,//单人副本的成绩, 击杀完BOSS后获得.
		
		MSG_C2F2B_REQ_KILL_ALL_MONSTER_IN_SINGLE_DUP = MSG_BASE_ID + 0x28010,// 在没有 BOSS 的关卡, 杀光所有的怪物就算是过关了.
		MSG_B2F2C_ACK_KILL_ALL_MONSTER_IN_SINGLE_DUP = MSG_BASE_ID + 0x38010,
		
		MSG_C2F2B_REQ_RELIVE_IN_SINGLE_DUP = MSG_BASE_ID + 0x2800D,// 0表示使用铜币复活, 1表示使用金币复活.
		MSG_B2F2C_ACK_RELIVE_IN_SINGLE_DUP = MSG_BASE_ID + 0x3800D,

		MSG_C2F2B_REQ_QUERY_PAY_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x28012,
		MSG_B2F2C_ACK_QUERY_PAY_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x38012,
		MSG_C2F2B_REQ_GET_PAY_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x28013,
		
		MSG_C2F2B_REQ_QUERY_FREE_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x28018,
		MSG_B2F2C_ACK_QUERY_FREE_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x38018,
		MSG_C2F2B_REQ_GET_FREE_PRIZES_SINGLE_DUP = MSG_BASE_ID + 0x28019,
		
		MSG_C2F2D_REQ_CHARACTER_INFO = MSG_BASE_ID + 0x26019, //请求个人信息.
		MSG_D2F2C_ACK_CHARACTER_INFO = MSG_BASE_ID + 0x36019,
		
		MSG_C2F2B_REQ_KILL_MONSTER_FOR_TASK = MSG_BASE_ID + 0x28017,//发送任务中的杀怪数.
		
        MSG_C2F2D_REQ_STARS_AWARD = MSG_BASE_ID + 0x26024,//查看篇章奖励.
        MSG_D2F2C_ACK_STARS_AWARD = MSG_BASE_ID + 0x36024,

		MSG_C2F2D_REQ_COMPLETED_INSTANCE = MSG_BASE_ID + 0x2601A,//请求已经完成的任务.
		MSG_D2F2C_ACK_COMPLETED_INSTANCE = MSG_BASE_ID + 0x3601A,
		
		MSG_C2F2D_REQ_RECVED_TASK_AWARD = MSG_BASE_ID + 0x26015,//领取任务奖励.
		MSG_D2F2C_ACK_RECVED_TASK_AWARD = MSG_BASE_ID + 0x36015,

		MSG_C2F2D_REQ_MASTERED_SKILL = MSG_BASE_ID + 0x2601B,//请求技能.
		MSG_D2F2C_ACK_MASTERED_SKILL = MSG_BASE_ID + 0x3601B,
		
		MSG_C2F2D_REQ_ALL_FIRST_LVL_SKILL = MSG_BASE_ID + 0x2601D,//请求玩家所有技能.
		MSG_D2F2C_ACK_ALL_FIRST_LVL_SKILL = MSG_BASE_ID + 0x3601D,
		
		MSG_C2F2D_REQ_EQUIP_SKILL = MSG_BASE_ID + 0x2601E,//请求玩家已经装备的技能.
		
		MSG_C2F2D_REQ_UPDATE_SKILL_LEVEL = MSG_BASE_ID + 0x2601C,//玩家升级技能.
		MSG_D2F2C_ACK_UPDATE_SKILL_LEVEL = MSG_BASE_ID + 0x3601C,
		
		MSG_C2F2D_REQ_RESET_SPEC_ATTRI = MSG_BASE_ID + 0x26021,//洗练.
		MSG_D2F2C_ACK_RESET_SPEC_ATTRI = MSG_BASE_ID + 0x36021,
		
		MSG_C2F2D_REQ_FIRST_LVL_TALENT = MSG_BASE_ID + 0x26025,//请求第一级天赋.
		MSG_D2F2C_ACK_FIRST_LVL_TALENT = MSG_BASE_ID + 0x36025,

        MSG_C2F2W_REQ_MATERIAL_SEARCH_PLAY = MSG_BASE_ID + 0x2A303,//道具寻访.(统一返回);

        MSG_C2F2W_REQ_SEARCH_PLAY = MSG_BASE_ID + 0x2A005,//进行寻访操作（非免费）.
        MSG_W2F2C_ACK_SEARCH_PLAY = MSG_BASE_ID + 0x3A005,

        MSG_C2F2B_COMB_ELITE_DUPLICATE = MSG_BASE_ID + 0x28181,
        MSG_B2C_ACK_COMB_ELITE_DUPLICATE = MSG_BASE_ID + 0x38181,

        MSG_C2F2B_COMB_DUPLICATE = MSG_BASE_ID + 0x28080,// 玩家请求扫荡关卡, 这个关卡必须是已完成的.
        MSG_B2C_ACK_COMB_DUPLICATE = MSG_BASE_ID + 0x38080,

        MSG_C2F2B_GET_COMB_ITEM = MSG_BASE_ID + 0x28081,// 玩家请求领取扫荡的道具.
        MSG_B2C_ACK_GET_COMB_ITEM = MSG_BASE_ID + 0x38081,

        MSG_C2F2B_GET_COMB_ELITE_ITEM = MSG_BASE_ID + 0x28182,//精英扫荡领取道具.
        MSG_B2C_ACK_GET_COMB_ELITE_ITEM = MSG_BASE_ID + 0x38182,

        MSG_C2F2B_COMB_ELITE_END = MSG_BASE_ID + 0x28183,//玩家精英扫荡结束.断开和 SPACE 的连接.

        MSG_C2F2B_COMB_END = MSG_BASE_ID + 0x28082,// 玩家扫荡结束.断开和 SPACE 的连接.

        MSG_C2F2W_REQ_FREE_SEARCH_PLAY = MSG_BASE_ID + 0x2A006,//进行免费寻访.
        MSG_W2F2C_ACK_FREE_SEARCH_PLAY = MSG_BASE_ID + 0x3A006,

        MSG_C2F2W_REQ_LUCKY_CHANCE = MSG_BASE_ID + 0x2A008,//机缘购买.
        MSG_W2F2C_ACK_LUCKY_CHANCE = MSG_BASE_ID + 0x3A008,

		MSG_C2F2W_REQ_ACTIVE_PLAY_SEARCH = MSG_BASE_ID + 0x2A00F,//玩家请求,激活寻访玩法.
		MSG_W2F2C_ACK_ACTIVE_PLAY_SEARCH = MSG_BASE_ID + 0x3A00F,

        MSG_C2F2W_REQ_SEARCH_PLAY_INFO = MSG_BASE_ID + 0x2A004,//玩家请求寻访信息.
        MSG_W2F2C_ACK_SEARCH_PLAY_INFO = MSG_BASE_ID + 0x3A004,

        MSG_C2F2D_REQ_GAME_ACTIVITY = MSG_BASE_ID + 0x26403,//客户端,请求查询游戏活动信息
        MSG_D2F2C_ACK_GAME_ACTIVITY = MSG_BASE_ID + 0x36403,

        MSG_C2F2W_REQ_SEARCH_EXCHANGE = MSG_BASE_ID + 0x2A007,//请求兑换奖励.
        MSG_W2F2C_ACK_SEARCH_EXCHANGE = MSG_BASE_ID + 0x3A007,

		MSG_C2F2D_REQ_MASTERED_TALENT = MSG_BASE_ID + 0x26022,//请求已经掌握的天赋.
		MSG_D2F2C_ACK_MASTERED_TALENT = MSG_BASE_ID + 0x36022,
		
		MSG_C2F2D_REQ_LEARN_TALENT = MSG_BASE_ID + 0x26023,//玩家主动学习天赋.
		MSG_D2F2C_ACK_LEARN_TALENT = MSG_BASE_ID + 0x36023,
		
		MSG_C2F2D_REQ_CUR_CHAPTER_COMPLETION = MSG_BASE_ID + 0x26026,// 玩家请求某个篇章的关卡完成进度, 比如某篇章有 5 个关卡, 完成了 3 个, 客户端就显示 3/5
		MSG_D2F2C_ACK_CUR_CHAPTER_COMPLETION = MSG_BASE_ID + 0x36026,
		
		MSG_C2F2D_REQ_GODCARD_BAG = MSG_BASE_ID + 0x26002,//请求神卡背包.
		MSG_D2F2C_ACK_GODCARD = MSG_BASE_ID + 0x36002,
		
		MSG_C2F2D_REQ_INSTALL_EQUIPMENT_GODCARD = MSG_BASE_ID + 0x26003,//请求装备神将卡.
		MSG_D2F2C_ACK_INSTALL_EQUIPMENT_GODCARD = MSG_BASE_ID + 0x36003, 
		
		MSG_C2F2D_REQ_INSTALL_TRANSFORM_GODCARD = MSG_BASE_ID + 0x26004,//装备变身卡.
		MSG_D2F2C_ACK_INSTALL_TRANSFORM_GODCARD = MSG_BASE_ID + 0x36004,//装备变身卡.
		
        MSG_C2F2D_REQ_SMELT_SOULE_CARD = MSG_BASE_ID + 0x26016,//练魂.
        MSG_D2F2C_ACK_SMELT_SOULE_CARD = MSG_BASE_ID + 0x36016,

		MSG_C2F2D_REQ_SWALLOW_GODCARD = MSG_BASE_ID + 0x2600C,//请求吞噬卡.
		MSG_D2F2C_ACK_SWALLOW_GODCARD = MSG_BASE_ID + 0x3600C,
		
		MSG_C2F2D_REQ_UP_STAR_CRAD = MSG_BASE_ID + 0x26017,//神卡升星.
		MSG_D2F2C_ACK_UP_STAR_CRAD = MSG_BASE_ID + 0x36017,
		
        MSG_C2F2D_REQ_RESET_GODCARD_TALENT = MSG_BASE_ID + 0x26008,//神卡天赋洗练.
        MSG_D2F2C_ACK_RESET_GODCARD_TALENT = MSG_BASE_ID + 0x36008,

		MSG_C2F2D_REQ_DESTINY_INFO = MSG_BASE_ID + 0x26028,//请求天命技能.
		MSG_D2F2C_ACK_DESTINY_INFO = MSG_BASE_ID + 0x36028,
		
		MSG_C2F2D_REQ_CREATE_DESTINY = MSG_BASE_ID + 0x26027,//创建天命技能.
		MSG_D2F2C_ACK_CREATE_DESTINY = MSG_BASE_ID + 0x36027,
		
		MSG_C2F2D_REQ_INJECT_DESTINY_SKILL = MSG_BASE_ID + 0x26029,//被注入的天命技能ID.
		MSG_D2F2C_ACK_INJECT_DESTINY_SKILL = MSG_BASE_ID + 0x36029,
		
		MSG_C2F2D_REQ_ACTIVE_GODCOMB_SKILL = MSG_BASE_ID + 0x2602B,//玩家请求，获取激活的神卡组合技能信息.
		MSG_D2F2C_ACK_ACTIVE_GODCOMB_SKILL = MSG_BASE_ID + 0x3602B,
		
		MSG_C2F2D_REQ_ACTIVING_DESTINY_SKILL = MSG_BASE_ID + 0x2602A,//激活的天命技能ID.
		MSG_D2F2C_ACK_ACTIVING_DESTINY_SKILL = MSG_BASE_ID + 0x3602A,
		
		MSG_C2F2D_REQ_GET_STAR_AWARD = MSG_BASE_ID + 0x26020,//领取篇章的评星奖励.
        MSG_D2F2C_ACK_GET_STAR_AWARD = MSG_BASE_ID + 0x36020,

        MSG_C2F2D_REQ_SP = MSG_BASE_ID + 0x26057,//时间来恢复体力.
        MSG_D2F2C_ACK_SP = MSG_BASE_ID + 0x36057,

		MSG_C2F_WRITE_LOG = MSG_BASE_ID + 0x2A304,//客户端通知记录日志.

		MSG_C2F2B_REQ_ENTER_HIGH_LADDER = MSG_BASE_ID + 0x28151,//请求进入天梯.
		MSG_B2F2C_ACK_ENTER_HIGH_LADDER = MSG_BASE_ID + 0x38151,

		MSG_C2F2B_REQ_HIGH_LADDER_RESULT = MSG_BASE_ID + 0x28152,//发送战斗结果.
		MSG_B2F2C_ACK_HIGH_LADDER_RESULT = MSG_BASE_ID + 0x38152,

		MSG_C2F2B_REQ_ENTER_REBRITH_TOWER = MSG_BASE_ID + 0x28140,//进入轮回之塔.
		MSG_B2F2C_ACK_ENTER_REBRITH_TOWER = MSG_BASE_ID + 0x38140,

		MSG_C2F2B_REQ_FAST_TRACK = MSG_BASE_ID + 0x28172,//快速扫荡.
		MSG_B2F2C_ACK_FAST_TRACK = MSG_BASE_ID + 0x38172,

		MSG_C2F2B_REQ_REBRITH_TOWER_CONFIG = MSG_BASE_ID + 0x28141,//请求轮回之塔配置信息.
		MSG_B2F2C_ACK_REBRITH_TOWER_CONFIG = MSG_BASE_ID + 0x38141,

		MSG_C2F2B_REQ_LEAVE_REBRITH_TOWER = MSG_BASE_ID + 0x28142,//请求离开轮回之塔.

		MSG_C2F2B_REQ_OPEN_CHANCE = MSG_BASE_ID + 0x28143,//请求开启挑战.
		MSG_B2F2C_ACK_OPEN_CHANCE = MSG_BASE_ID + 0x38143,

		MSG_C2F2B_REQ_TOWER_DROPS_INFO = MSG_BASE_ID + 0x28144,//请求获取掉落物品信息.
		MSG_B2F2C_ACK_TOWER_DROPS_INFO = MSG_BASE_ID + 0x38144,

		MSG_C2F2B_REQ_PICKUP_EXP = MSG_BASE_ID + 0x28145,//请求拾取经验.
		MSG_B2F2C_ACK_PICKUP_EXP = MSG_BASE_ID + 0x38145,//no use

		MSG_C2F2B_REQ_PICKUP_GOODS = MSG_BASE_ID + 0x28146,//请求拾取物品.
		MSG_B2F2C_ACK_PICKUP_GOODS = MSG_BASE_ID + 0x38146,//no use

		MSG_C2F2B_REQ_PAY_TOWER = MSG_BASE_ID + 0x28147,//请求付费操作.
		MSG_B2F2C_ACK_PAY_TOWER = MSG_BASE_ID + 0x38147,

		MSG_C2F2B_REQ_THROUGH_FLOOR = MSG_BASE_ID + 0x28148,//请求通过一层.
		MSG_B2F2C_ACK_THROUGH_FLOOR = MSG_BASE_ID + 0x38148,

		MSG_C2F2B_REQ_RECEIVE_CHANCE_AWARDS = MSG_BASE_ID + 0x28150,//请求领取挑战所有奖励.
		MSG_B2F2C_ACK_RECEIVE_CHANCE_AWARDS = MSG_BASE_ID + 0x38150,

		MSG_C2F2D_REQ_MULTI_PLAYER_BOSS_UI_INFO = MSG_BASE_ID + 0x2602C,
		MSG_D2F2C_ACK_MULTI_PLAYER_BOSS_UI_INFO = MSG_BASE_ID + 0x3602C,
		
		MSG_C2F2D_REQ_MULTI_PLAYER_BOSS_AWARD = MSG_BASE_ID + 0x26039,//客户端查询多人 BOSS 排行榜奖励.
		MSG_D2F2C_ACK_MULTI_PLAYER_BOSS_AWARD = MSG_BASE_ID + 0x36039,
		
		MSG_C2F2D_REQ_GET_MULTI_PLAYER_BOSS_AWARD = MSG_BASE_ID + 0x2603A,//客户端领取多人 BOSS 排行榜奖励.
		MSG_D2F2C_ACK_GET_MULTI_PLAYER_BOSS_AWARD = MSG_BASE_ID + 0x3603A,

		MSG_C2F2B_REQ_ENTER_BOSS_ROOM = MSG_BASE_ID + 0x28101,//玩家进入BOSS房间.
		MSG_B2F2C_ACK_ENTER_BOSS_ROOM = MSG_BASE_ID + 0x38101,//进入多人BOSS是否成功.
		MSG_C2F2B_REQ_OTHER_PLAYER_INFO = MSG_BASE_ID + 0x28102,//请求房间内其他玩家的个人基本信息.
		MSG_B2F2C_ACK_OTHER_PLAYER_INFO = MSG_BASE_ID + 0x38102,//返回其他玩家信息.
		MSG_C2F2B_REQ_LEVEA_BOSS_ROOM = MSG_BASE_ID + 0x28103,//玩家离开BOSS房间.
		MSG_B2F2C_ONE_PLAYER_ENTER = MSG_BASE_ID + 0x38105,//服务器告诉房间内的玩家,有新玩家进入房间.
		MSG_B2F2C_ACK_LEVEA_BOSS_ROOM = MSG_BASE_ID + 0x38103,//通知其他玩家,有人离开BOSS房间.
		
		MSG_B2F2C_SEND_ROOM_BOSS_INFO = MSG_BASE_ID + 0x3810B,//向客户端发送BOSS信息.
		MSG_B2F2C_ROOM_BOSS_MOVE = MSG_BASE_ID + 0x3810C,//BOSS在房间内移动.
		MSG_B2F2C_ROOM_BOSS_ATTACK = MSG_BASE_ID + 0x3810D,
		
		MSG_B2F2C_CONSUME_FOR_RELIVE_IN_BOSS_ROOM = MSG_BASE_ID + 0x38111,//复活信息.
		MSG_C2F2B_REQ_RELIVE_IN_BOSS_ROOM = MSG_BASE_ID + 0x28112,//请求复活.
		MSG_B2F2C_ACK_RELIVE_IN_BOSS_ROOM = MSG_BASE_ID + 0x38112,//返回复活.
		
		MSG_B2F2C_ROOM_BOSS_AWARD = MSG_BASE_ID + 0x38110,//杀死多人BOSS后, 所获得的装备和碎片.
		MSG_B2F2C_ROOM_BOSS_RESULT = MSG_BASE_ID + 0x3810E,//杀死BOSS后的成绩结算, 包括角色名, 积分, 经验.
		
		MSG_C2F2B_REQ_MOVE_IN_BOSS_ROOM = MSG_BASE_ID + 0x28104,//玩家在BOSS房间中移动.
		MSG_B2F2C_PLAYER_MOVE_IN_BOSS_ROOM = MSG_BASE_ID + 0x38104,//把移动者的坐标信息, 广播给其他玩家.
		MSG_C2F2B_REQ_DECEASE = MSG_BASE_ID + 0x28106,//玩家的死亡消息.
		MSG_B2F2C_ACK_DECEASE = MSG_BASE_ID + 0x38106,
		MSG_C2F2B_REQ_BUFF_CHANGE = MSG_BASE_ID + 0x28107,//玩家和BOSS的BUFF改变消息.
		MSG_B2F2C_ACK_BUFF_CHANGE = MSG_BASE_ID + 0x38107,
		MSG_C2F2B_REQ_HP_CHANGE = MSG_BASE_ID + 0x28108,//玩家和BOSS的生命改变消息.
		MSG_B2F2C_ACK_HP_CHANGE = MSG_BASE_ID + 0x38108,
		MSG_C2F2B_REQ_ANIMATION_CHANGE = MSG_BASE_ID + 0x28109,//玩家改变动画消息.
		MSG_B2F2C_ACK_ANIMATION_CHANGE = MSG_BASE_ID + 0x38109,
		MSG_C2F2B_REQ_TRANSFORMATE = MSG_BASE_ID + 0x2810A,//玩家变身消息.
		MSG_B2F2C_ACK_TRANSFORMATE = MSG_BASE_ID + 0x3810A,

		//pvp start---------------
		MSG_C2F2B_REQ_ENTER_PVP_FIGHT = MSG_BASE_ID + 0x28175,//客户端请求进入PVP战斗.
		MSG_B2F2C_ACK_ENTER_PVP_FIGHT = MSG_BASE_ID + 0x38175,

		MSG_B2F2C_REQ_PVP_FIGHT_READY = MSG_BASE_ID + 0x28176,
		MSG_B2F2C_PUSH_PVP_FIGHT_INFO = MSG_BASE_ID + 0x38177,
		MSG_B2F2C_PUSH_PVP_CONFIG = MSG_BASE_ID + 0x3817E,
		MSG_B2F2C_PUSH_TIME_OUT = MSG_BASE_ID + 0x3817C,

		MSG_C2F2B_LEAVE_PVPROOM = MSG_BASE_ID + 0x2817D,
		MSG_B2F2C_LEAVE_PVPROOM = MSG_BASE_ID + 0x3817D,
		MSG_C2F2B_REQ_PVP_DEATH = MSG_BASE_ID + 0x28179,
		MSG_C2F2B_PVP_COMMON_MSG = MSG_BASE_ID + 0x2817A,
		MSG_B2F2C_PVP_COMMON_MSG = MSG_BASE_ID + 0x3817A,
		MSG_B2F2C_PVP_FIGHT_CLOSE = MSG_BASE_ID + 0x2817B,
		MSG_W2F2C_PUSH_INIDVIDUAL_ATHLETIC_AWARDS = MSG_BASE_ID + 0x3A31F,
		MSG_B2F2C_PUSH_CLIENT_UI_FRAME = MSG_BASE_ID + 0x3817F,
		MSG_B2F2C_PUSH_KILL_MESSAGE = MSG_BASE_ID + 0x38180,
		//pvp end-----------------

		MSG_C2F2W_REQ_ENTER_GAME_CITY = MSG_BASE_ID + 0x2A20C,//进入主城消息.
		MSG_C2F2W_REQ_LEAVE_GAME_CITY = MSG_BASE_ID + 0x2A20D,//离开主城消息.

		MSG_C2F2W_REQ_MOVEIN_GAME_CITY = MSG_BASE_ID + 0x2A20E,//主城移动消息.
		MSG_W2F2C_PUSH_GAMEROOM_POSITION = MSG_BASE_ID + 0x3A20F,//PUSH房间列表位置信息.

		MSG_C2F2D_REQ_OTHER_INFO = MSG_BASE_ID + 0x2603B,//向DB请求其他玩家的信息.
		MSG_D2F2C_ACK_OTHER_INFO = MSG_BASE_ID + 0x3603B,

		MSG_C2F2W_REQ_ACTIVE_SURPRISE_MEET = MSG_BASE_ID + 0x2A010,//玩家请求，激活奇缘玩法.
		MSG_W2F2C_ACK_ACTIVE_SURPRISE_MEET = MSG_BASE_ID + 0x3A010,

		MSG_C2F2W_REQ_PSSM_INFO = MSG_BASE_ID + 0x2A009,//获取奇缘玩法信息.
		MSG_W2F2C_ACK_PSSM_INFO = MSG_BASE_ID + 0x3A009,

		MSG_C2F2W_REQ_PSSM_EXPLORE = MSG_BASE_ID + 0x2A00A,//玩家请求，执行探索操作.
		MSG_W2F2C_ACK_PSSM_EXPLORE = MSG_BASE_ID + 0x3A00A,

		MSG_C2F2W_REQ_PSSM_REFRESH_ACTIVE = MSG_BASE_ID + 0x2A00C,//刷新商店.
		MSG_W2F2C_ACK_PSSM_REFRESH_ACTIVE = MSG_BASE_ID + 0x3A00C,

		MSG_C2F2W_REQ_PSSM_DEAL_ACTIVE = MSG_BASE_ID + 0x2A00D,//购买物品.
		MSG_W2F2C_ACK_PSSM_DEAL_ACTIVE = MSG_BASE_ID + 0x3A00D,

        MSG_C2F2D_REQ_MAILE_ANNEXE = MSG_BASE_ID + 0x26054,//提取邮件附件.
        MSG_D2F2C_ACK_MAILE_ANNEXE = MSG_BASE_ID + 0x36054,

        MSG_C2F2D_REQ_DELETE_MAILE = MSG_BASE_ID + 0x26053,//删除邮件.
        MSG_D2F2C_ACK_DELETE_MAILE = MSG_BASE_ID + 0x36053,

        MSG_C2F2D_REQ_MAILE_INFO = MSG_BASE_ID + 0x26052,
        MSG_D2F2C_ACK_MAILE_INFO = MSG_BASE_ID + 0x36052,//读取邮件的详细信息
        
        MSG_D2F2C_PUSH_MAILE_INDEX_INFO = MSG_BASE_ID + 0x36051,//push邮件.

        //public

        MSG_C2F2W_REQ_COMMON_MAILE_INDEX_NODE = MSG_BASE_ID + 0x2A210,//公用邮件.
        MSG_W2F2C_ACK_COMMON_MAILE_INDEX_NODE = MSG_BASE_ID + 0x3A210,

        MSG_C2F2W_REQ_INDEX_INFO = MSG_BASE_ID + 0x2A211,//获取索引节点的索引信息.
        MSG_W2F2C_ACK_INDEX_INFO = MSG_BASE_ID + 0x3A211,

        MSG_C2F2W_REQ_COMMON_MAILE_INFO = MSG_BASE_ID + 0x2A212,//获取共有邮件详细信息.
        MSG_W2F2C_ACK_COMMON_MAILE_INFO = MSG_BASE_ID + 0x3A212,

        MSG_C2F2W_REQ_PICKUP_COMMON_MAILE = MSG_BASE_ID + 0x2A213,//提取共有邮件附件.
        MSG_W2F2C_ACK_PICKUP_COMMON_MAILE = MSG_BASE_ID + 0X3A213,

        MSG_C2F2W_REQ_DELETE_COMMON_MAILE = MSG_BASE_ID + 0x2A215,//删除共有邮件
        MSG_W2F2C_ACK_DELETE_COMMON_MAILE = MSG_BASE_ID + 0x3A215,

        MSG_W2F2C_PUSH_COMMON_MAILE_INDEX = MSG_BASE_ID +  0x2A214,

        MSG_C2F2D_REQ_MAILE_INDEX_INFO = MSG_BASE_ID + 0x26050,//获取邮件索引.
        MSG_D2F2C_ACK_MAILE_INDEX_INFO = MSG_BASE_ID + 0x36050,

        MSG_C2F2W_REQ_FRI = MSG_BASE_ID + 0x2A101,//请求好友主体消息.
        MSG_W2F2C_ACK_FRI = MSG_BASE_ID + 0x3A101,

        MSG_C2F2W_REQ_ISAGREE_FRIEND_APPLY = MSG_BASE_ID + 0x2A117,//同意或者拒绝好友.
        MSG_W2F2C_ACK_ISAGREE_FRIEND_APPLY = MSG_BASE_ID + 0x3A117,

        MSG_C2F2W_REQ_GIVEN_GOODS = MSG_BASE_ID + 0x2A115,//赠送给某好友的好友ID.
        MSG_W2F2C_ACK_GIVEN_GOODS = MSG_BASE_ID + 0x3A115,

        MSG_C2F2W_REQ_GOT_GOODS = MSG_BASE_ID + 0x2A116,//玩家接收物品协议.
        MSG_W2F2C_ACK_GOT_GOODS = MSG_BASE_ID + 0x3A116,

        MSG_C2F2W_REQ_ADD_FRI = MSG_BASE_ID + 0x2A102,////玩家请求添加好友消息.
        MSG_W2F2C_ACK_ADD_FRI = MSG_BASE_ID + 0x3A102,

        MSG_C2F2W_REQ_SET_BEST_FRIEND = MSG_BASE_ID + 0x2A119,//添加删除生死之交.
        MSG_W2F2C_ACK_SET_BEST_FRIEND = MSG_BASE_ID + 0x3A119,

        MSG_C2F2W_REQ_DELETE_FRI = MSG_BASE_ID + 0x2A103,//玩家请求删除好友消息.
        MSG_W2F2C_ACK_DELETE_FRI = MSG_BASE_ID + 0x3A103,

        MSG_C2F2W_REQ_RECV_ONLINE_REWARD = MSG_BASE_ID + 0x2A11A,//领取生死之交每日在线奖励.
        MSG_W2F2C_ACK_RECV_ONLINE_REWARD = MSG_BASE_ID + 0x3A11A,

        MSG_C2F2W_REQ_RECV_10_MINUTES_ONLINE_REWARD = MSG_BASE_ID + 0x2A11B,//领取生死之交10分钟在线奖励.
        MSG_W2F2C_ACK_RECV_10_MINUTES_ONLINE_REWARD = MSG_BASE_ID + 0x3A11B,

        MSG_W2F2C_PUSH_SNS_SELF = MSG_BASE_ID + 0xA2001,//服务器推送 消息(好友). 

        MSG_C2F2D_REQ_SURVEY_QUESTION_NUM = MSG_BASE_ID + 0x2605B,//问卷.
        MSG_D2F2C_ACK_SURVEY_QUESTION_NUM = MSG_BASE_ID + 0x3605B,

        MSG_C2F2D_REQ_ANSWER_SURVEY_QUESTION = MSG_BASE_ID + 0x2605C,//上传问卷回答.
        MSG_D2F2C_ACK_ANSWER_SURVEY_QUESTION = MSG_BASE_ID + 0x3605C,

        MSG_C2F2D_REQ_RECV_SURVEY_AWARD = MSG_BASE_ID + 0x2605D,//领取问卷奖励.
        MSG_D2F2C_ACK_RECV_SURVEY_AWARD = MSG_BASE_ID + 0x3605D,

        MSG_C2F2W_REQ_ELITE_COPY_INFO = MSG_BASE_ID + 0x2A084,////玩家请求精英副本数据.
        MSG_W2F2C_ACK_ELITE_COPY_INFO = MSG_BASE_ID + 0x3A084,

        MSG_C2F2W_REQ_ELITE_COPY_PLAYER = MSG_BASE_ID + 0x2A088,//请求非好友的玩家列表.
        MSG_W2F2C_ACK_ELITE_COPY_PLAYER = MSG_BASE_ID + 0x3A088,

        MSG_C2F2W_REQ_ELITE_COPY_CANCLE_CD = MSG_BASE_ID + 0x2A087,//请求取消好友的cd时间
        MSG_W2F2C_ACK_ELITE_COPY_CANCLE_CD = MSG_BASE_ID + 0x3A087,

        MSG_C2F2D_REQ_READ_SHIZHUANG_BAG = MSG_BASE_ID + 0x26313,//请求时装信息.
        MSG_D2F2C_ACK_READ_SHIZHUANG_BAG = MSG_BASE_ID + 0x36313,

        MSG_C2F2D_REQ_SHOW_SHIZHUANG = MSG_BASE_ID + 0x26315,//设置时装是否显示.
        MSG_D2F2C_ACK_SHOW_SHIZHUANG = MSG_BASE_ID + 0x36315,

        MSG_C2F2D_REQ_WEAR_SHIZHUANG = MSG_BASE_ID + 0x26314,//请求穿戴装备.
        MSG_D2F2C_ACK_WEAR_SHIZHUANG = MSG_BASE_ID + 0x36314,

        MSG_C2F2W_REQ_BUY_ELITE_COPY_CHALLENGE_TIMES = MSG_BASE_ID + 0x2A085,//玩家请求购买挑战次数.
        MSG_W2F2C_ACK_BUY_ELITE_COPY_CHALLENGE_TIMES = MSG_BASE_ID + 0x3A085,

        MSG_C2F2W_REQ_PLAYER_ONLINE_AWARD_INFO = MSG_BASE_ID + 0x2A08C,//玩家请求在线奖励记录.
        MSG_W2F2C_ACK_PLAYER_ONLINE_AWARD_INFO = MSG_BASE_ID + 0x3A08C,

        MSG_C2F2W_REQ_RECV_PLAYER_ONLINE_AWARD = MSG_BASE_ID + 0x2A08D,
        MSG_W2F2C_ACK_RECV_PLAYER_ONLINE_AWARD = MSG_BASE_ID + 0x3A08D,

        MSG_C2F2D_REQ_BEAST_GOD_INFO = MSG_BASE_ID + 0x2606F,//请求角色兽神相关信息.
        MSG_D2F2C_ACK_BEAST_GOD_INFO = MSG_BASE_ID + 0x3606F,

        MSG_C2F2D_REQ_BEAST_GOD_UP_STAR = MSG_BASE_ID + 0x26070,//请求培养升星.
        MSG_D2F2C_ACK_BEAST_GOD_UP_STAR = MSG_BASE_ID + 0x36070,

        MSG_C2F2D_REQ_BEAST_GOD_UP_SKILL = MSG_BASE_ID + 0x26071, //请求升级兽神技能.
        MSG_D2F2C_ACK_BEAST_GOD_UP_SKILL = MSG_BASE_ID + 0x36071,

        MSG_C2F2D_REQ_BEAST_GOD_UP_CHANGE = MSG_BASE_ID + 0x26072,//请求更换兽神.
        MSG_D2F2C_ACK_BEAST_GOD_UP_CHANGE = MSG_BASE_ID + 0x36072,

        MSG_C2F2D_REQ_BEAST_GOD_ACTIVATION = MSG_BASE_ID + 0x26073,//激活兽神.
        MSG_D2F2C_ACK_BEAST_GOD_ACTIVATION = MSG_BASE_ID + 0x36073,

		MSG_D2F2C_PUSH_VIPLEVEL_CHANGE = MSG_BASE_ID + 0x3630A,//vip等级变更的消息.

		MSG_C2F2D_REQ_ACTIVE_GAME_TASK = MSG_BASE_ID + 0x2603D,//激活任务系统.no use
		MSG_D2F2C_ACK_ACTIVE_GAME_TASK = MSG_BASE_ID + 0x3603D,

		MSG_C2F2D_REQ_GET_GAME_TASK = MSG_BASE_ID + 0x2603E,//获取任务系统信息.
		MSG_D2F2C_ACK_GET_GAME_TASK = MSG_BASE_ID + 0x3603E, 

        MSG_D2F2C_PUSH_PLOTTASK_COMPLETE = MSG_BASE_ID + 0x36308,//主动推送任务已经完成.

		MSG_C2F2D_REQ_RECEIVE_TASK = MSG_BASE_ID + 0x2603F,//接取任务(主线).
		MSG_D2F2C_ACK_RECEIVE_TASK = MSG_BASE_ID + 0x3603F,

        MSG_C2F2D_REQ_BRANCH_TASK_AWARD = MSG_BASE_ID + 0x26309,//请求领取支线任务奖励消息
        MSG_D2F2C_ACK_BRANCH_TASK_AWARD = MSG_BASE_ID + 0x36309,

        MSG_C2F2D_EQU_COMPOSE_GOODS = MSG_BASE_ID + 0x26056,// 卡片合成.
        MSG_D2F2C_ACK_COMPOSE_GOODS = MSG_BASE_ID + 0x36056,

        MSG_C2F2W_REQ_SEND_COMMUNICATION_INFO = MSG_BASE_ID + 0x2A011,//聊天 发送消息
        MSG_W2F2C_PUSH_COMMUNICATION_INFO = MSG_BASE_ID + 0xA2003,//接受服务器发的聊天信息 私聊
        MSG_W2F2C_BROADCAST_COMMUNICATION = MSG_BASE_ID + 0xA2004,//广播 所有玩家 聊天信息

		MSG_D2F2C_PUSH_COMPLETE_TASK = MSG_BASE_ID + 0x36049,//服务器推送信息,判断任务是否完成.

        MSG_C2F2D_REQ_OTHER_CHARACTER_INFO = MSG_BASE_ID + 0x26058, //通过玩家ID获取玩家信息
        MSG_D2F2C_ACK_OTHER_CHARACTER_INFO = MSG_BASE_ID + 0x36058,

        MSG_C2F2W_REQ_ZHANJIANG_GUANZHI_ID = MSG_BASE_ID + 0x2A0A9,//查看角色的ID
        MSG_W2F2C_ACK_ZHANJIANG_GUANZHI_ID = MSG_BASE_ID + 0x3A0A9,

        MSG_C2F2W_REQ_REBRITH_TOWER_INFO = MSG_BASE_ID + 0x2A012,//获取玩家轮回之塔信息
        MSG_W2F2C_ACK_REBRITH_TOWER_INFO = MSG_BASE_ID + 0x3A012,

        MSG_C2F2W_REQ_TOWER_RANK_INFO = MSG_BASE_ID + 0x2A013,//获取玩家的轮回之塔排行信息
        MSG_W2F2C_ACK_TOWER_RANK_INFO = MSG_BASE_ID + 0x3A013,

        MSG_C2F2W_REQ_BUY_KEY = MSG_BASE_ID + 0x2A014,//购买轮回之塔钥匙
        MSG_W2F2C_ACK_BUY_KEY = MSG_BASE_ID + 0x3A014,

        MSG_C2F2W_REQ_UP_TOWER = MSG_BASE_ID + 0x2A015,//轮回之塔晋升
        MSG_W2F2C_ACK_UP_TOWER = MSG_BASE_ID + 0x3a015,

        MSG_C2F2W_REQ_RECEIVE_REBRITH_FRIST_AWARDS = MSG_BASE_ID + 0x2A016,//轮回之塔,领取首次通关奖励
        MSG_C2F2W_ACK_RECEIVE_REBRITH_FRIST_AWARDS = MSG_BASE_ID + 0x3A016,

        MSG_C2F2W_REQ_RECEIVE_REBRITH_RANK_AWARDS = MSG_BASE_ID + 0x2A017,//轮回之塔，领取排行榜奖励
        MSG_C2F2W_ACK_RECEIVE_REBRITH_RANK_AWARDS = MSG_BASE_ID + 0x3A017,

        MSG_C2F2W_REQ_LADDER_INFO = MSG_BASE_ID + 0x2A018,//玩家请求天梯界面信息
        MSG_C2F2W_ACK_LADDER_INFO = MSG_BASE_ID + 0x3A018,

        MSG_C2F2W_REQ_LADDER_CHANGE_CHALLENGER_INFO = MSG_BASE_ID + 0x2A01E,//玩家请求挑战者信息
        MSG_C2F2W_ACk_LADDER_CHANGE_CHALLENGER_INFO = MSG_BASE_ID + 0x3A01E,

        MSG_W2F2C_PUSH_TI_CHU_GONG_HUI = MSG_BASE_ID + 0x3A333,//玩家被踢出公会

		MSG_C2F2B_REQ_ENTER_FAM = MSG_BASE_ID + 0x28153,//请求,进入秘境.
		MSG_B2F2C_ACK_ENTER_FAM = MSG_BASE_ID + 0x38153,

		MSG_C2F2B_REQ_FAM_INFO = MSG_BASE_ID + 0x28156,//客户端请求秘境信息.
		MSG_B2F2C_ACK_FAM_INFO = MSG_BASE_ID + 0x38156,

		MSG_C2F2B_REQ_FOR_RELIVE_IN_FAM = MSG_BASE_ID + 0x28155,//秘境中的复活请求消息.
		MSG_B2F2C_ACK_FOR_RELIVE_IN_FAM = MSG_BASE_ID + 0x38155,

		MSG_C2F2B_REQ_RECV_FAM_AWARD = MSG_BASE_ID + 0x28154,//秘境战斗结束领取奖励.
		MSG_B2F2C_ACK_RECV_FAM_AWARD = MSG_BASE_ID + 0x38154,

		MSG_B2F2C_ACK_RECV_FAM_AWARD_ADD_MESSAGE = MSG_BASE_ID + 0x38157,

        MSG_C2F2W_REQ_LADDER_RECV_TARGET_AWARD = MSG_BASE_ID + 0x2A01B,//玩家请求领取每日目标奖励协议.
        MSG_C2F2W_ACK_LADDER_RECV_TARGET_AWARD = MSG_BASE_ID + 0x3A01B,

        MSG_C2F2W_REQ_LADDER_RANK_LIST_INFO = MSG_BASE_ID + 0x2A01C,//请求排行榜协议.
        MSG_C2F2W_ACK_LADDER_RANK_LIST_INFO = MSG_BASE_ID + 0x3A01C,

        MSG_C2F2W_REQ_INDIVIDUAL_ATHETIC_RANK_INFO = MSG_BASE_ID + 0x2A320,//请求个人竞技排行的数据
        MSG_W2F2C_ACK_INDIVIDUAL_ATHETIC_RANK_INFO = MSG_BASE_ID + 0x3A320,

        MSG_C2F2W_REQ_LADDER_CHALLENGE_RECORD_INFO = MSG_BASE_ID + 0x2A01F,//请求挑战记录信息协议.
        MSG_C2F2W_ACK_LADDER_CHALLENGE_RECORD_INFO = MSG_BASE_ID + 0x3A01F,

        MSG_C2F2W_REQ_LADDER_RECV_RANK_AWARD = MSG_BASE_ID + 0x2A019,//领取天梯排行奖励协议.
        MSG_C2F2W_ACk_LADDER_RECV_RANK_AWARD = MSG_BASE_ID + 0x3A019,

        MSG_C2F2W_REQ_LADDER_BUY_CHALLENGE_COUNT = MSG_BASE_ID + 0x2A01A,//购买天梯挑战次数.
        MSG_C2F2W_ACK_LADDER_BUY_CHALLENGE_COUNT = MSG_BASE_ID + 0x3A01A,

        MSG_W2F2C_RADIO_COMMUNICATION = MSG_BASE_ID + 0xA2005,//服务器广播消息 玩家消息

        MSG_C2F2D_REQ_LOGIN_REWARD = MSG_BASE_ID + 0x26059,//玩家登陆领取每日登录奖励
        MSG_D2F2C_ACK_LOGIN_REWARD = MSG_BASE_ID + 0x36059,

        MSG_C2F2D_REQ_LOGIN_REWARD_FINISHED = MSG_BASE_ID + 0x2605A,//玩家是否已领取每日登录奖励
        MSG_D2F2C_ACK_LOGIN_REWARD_FINISHED = MSG_BASE_ID + 0x3605A,

        MSG_C2F2D_REQ_COMPOSE_PROPS = MSG_BASE_ID + 0x26065,//合成道具
        MSG_D2F2C_ACK_COMPOSE_PROPS = MSG_BASE_ID + 0x36065,

        MSG_C2F2W_REQ_FAM_INFO = MSG_BASE_ID + 0x2A07B,//请求秘境信息
        MSG_W2F2C_ACK_FAM_INFO = MSG_BASE_ID + 0x3A07B,

        MSG_C2F2W_PLAYER_INVITATION = MSG_BASE_ID + 0x2A202,//多人BOSS邀请玩家
        MSG_C2F2W_ACK_PLAYER_INVITATION = MSG_BASE_ID + 0x3A202,

        MSG_C2F2W_REQ_JOIN_TEAM = MSG_BASE_ID + 0x2A203,//玩家请求进入多人BOSS房间
        MSG_W2F2C_ACK_JOIN_TEAM = MSG_BASE_ID + 0x3A203,

		MSG_W2F2C_PUSH_PLAYER_ENTER = MSG_BASE_ID + 0x2A204,// 服务器告诉队伍内的玩家, 有新玩家进入队伍

        MSG_C2F2W_PLAYER_KICK_PLAYER = MSG_BASE_ID + 0x2A205,//多人BOSS踢人
		MSG_C2F2W_ACK_PLAYER_KICK_PLAYER = MSG_BASE_ID + 0x3A205,//多人BOSS踢人

        MSG_W2F2C_PUSH_KICKEDOUT = MSG_BASE_ID + 0x2A20B,// World服务器向玩家推送被踢出队伍

        MSG_C2F2W_REQ_CREATE_TEAM = MSG_BASE_ID + 0x2A201,//多人BOSS创建房间
        MSG_W2F2C_ACK_CREATE_TEAM = MSG_BASE_ID + 0x3A201,

		MSG_W2F2C_PUSH_PLAYER_QUIT = MSG_BASE_ID + 0x3A207,// 服务器告诉队伍内的玩家, 有玩家离开队伍

        MSG_C2F2W_REQ_PLAYER_EXIT_TEAM = MSG_BASE_ID + 0x2A206,// 玩家退出队伍
        MSG_W2F2C_ACK_PLAYER_EXIT_TEAM = MSG_BASE_ID + 0x3A206,

        MSG_C2F2W_REQ_QUICK_JOIN_TEAM = MSG_BASE_ID + 0x2A209,// 玩家请求快速进入队伍
        MSG_W2F2C_ACK_QUICK_JOIN_TEAM = MSG_BASE_ID + 0x3A209,

        MSG_C2F2W_REQ_START_MULTIPLAYDUP =  MSG_BASE_ID + 0x2A208,// 玩家请求开启组队副本（多人boss）
        MSG_W2F2C_ACK_START_MULTIPLAYDUP = MSG_BASE_ID + 0x3A208,

        MSG_W2F2C_PUSH_ENTER_MULTIPLAYDUP = MSG_BASE_ID + 0x2A20A,// World服务器向玩家推送进入多人副本

        MSG_C2F2W_REQ_PLAYER_AWARD_INFO = MSG_BASE_ID + 0x2A089, //请求玩家的在线奖励信息.
        MSG_W2F2C_ACK_PLAYER_AWARD_INFO = MSG_BASE_ID + 0x3A089,

        MSG_C2F2W_REQ_SIGN_IN = MSG_BASE_ID + 0x2A08A, //玩家请求签到.
        MSG_W2F2C_ACK_SIGN_IN = MSG_BASE_ID + 0x3A08A,

		MSG_C2F2W_REQ_SIGN_IN_AWARD = MSG_BASE_ID + 0x2A08B,//玩家请求领取签到奖励.
        MSG_W2F2C_ACK_SIGN_IN_AWARD = MSG_BASE_ID + 0x3A08B,

        MSG_C2F2W_REQ_RECV_GROW_UP_AWARD = MSG_BASE_ID + 0x2A08E,//玩家领取成长奖励.
        MSG_W2F2C_ACK_RECV_GROW_UP_AWARD = MSG_BASE_ID + 0x3A08E,

        MSG_D2F2C_PUSH_RECEIVE_GIFT = MSG_BASE_ID + 0x2606B,//DB服务器通知客户端礼包领取信息

        MSG_C2F2D_REQ_IS_BOSSROOM_ACTIVITY = MSG_BASE_ID + 0x26101,//客户端请求是否能进入多人boss房间
        MSG_C2F2D_ACK_IS_BOSSROOM_ACTIVITY = MSG_BASE_ID + 0x36101,

        MSG_C2F2D_REQ_RANDOM_GOODS = MSG_BASE_ID + 0x26102,//使用物品
        MSG_D2F2C_ACK_RANDOM_GOODS = MSG_BASE_ID + 0x36102,

		MSG_C2F2D_PUSH_UPDATE_CAHRINFO = MSG_BASE_ID + 0x26203,//提醒服务器刷新玩家战力

        MSG_C2F2D_REQ_CARD_DETAILEN_INFO = MSG_BASE_ID + 0x26205,//客户端请求获得礼包物品.
        MSG_D2F2C_ACK_CARD_DETAILEN_INFO = MSG_BASE_ID + 0x36205,


		MSG_C2F2W_REQ_RANK_INFO = MSG_BASE_ID + 0x2A092,//请求排行榜信息.
		MSG_W2F2C_ACK_RANK_INFO = MSG_BASE_ID + 0x3A092,//

		MSG_C2F2W_REQ_WORSHIP_RANK = MSG_BASE_ID + 0x2A093,//请求膜拜
		MSG_W2F2C_ACK_WORSHIP_RANK = MSG_BASE_ID + 0x3A093,//
        MSG_W2F2C_ACK_PLAYER_RANK_HAD_REFRESHED_DATA = MSG_BASE_ID + 0x3A096,//重新打开面板

		MSG_C2F2W_REQ_LV_RANK_PLAYER_INFO = MSG_BASE_ID + 0x2A094,//请求等级排行以及玩家数据
		MSG_W2F2C_ACK_LV_RANK_PLAYER_INFO = MSG_BASE_ID + 0x3A094,//

		MSG_C2F2W_REQ_PLAYER_RANK_INFO = MSG_BASE_ID + 0x2A095,//请求膜拜相关ID集合
		MSG_W2F2C_ACK_PLAYER_RANK_INFO = MSG_BASE_ID + 0x3A095,//请求膜拜相关ID集合

		MSG_C2F2D_REQ_WING_INFO = MSG_BASE_ID + 0x2606C,//请求角色翅膀信息
		MSG_D2F2C_ACK_WING_INFO = MSG_BASE_ID + 0x3606C,//请求角色翅膀信息

		MSG_C2F2D_REQ_EXCHANGE_WING = MSG_BASE_ID + 0x2606D,//请求兑换翅膀
		MSG_D2F2C_ACK_EXCHANGE_WING = MSG_BASE_ID + 0x3606D,

		MSG_C2F2D_REQ_WEAR_WING = MSG_BASE_ID + 0x2606E,//请求兑换翅膀
		MSG_D2F2C_ACK_WEAR_WING = MSG_BASE_ID + 0x3606E,//请求兑换翅膀

        MSG_C2F2D_REQ_WING_UP_LEVEL_INFO = MSG_BASE_ID + 0x26077,//请求翅膀升阶
        MSG_D2F2C_ACK_WING_UP_LEVEL_INFO = MSG_BASE_ID + 0x36077,//返回翅膀升阶

        MSG_C2F2D_REQ_ROUSE_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID + 0x26301,// 装备觉醒，不支持金币觉醒
        MSG_D2F2C_ACK_ROUSE_EQUIPMENT_BY_MATERIAL = MSG_BASE_ID + 0x36301,

        MSG_C2F2W_REQ_RECV_VIPLEVELGIFT = MSG_BASE_ID + 0x2A302,// 领取VIP等级礼包
        MSG_W2F2C_ACK_RECV_VIPLEVELGIFT = MSG_BASE_ID + 0x3A302,

        MSG_C2F2W_REQ_VIPLEVELGIFT_STATE = MSG_BASE_ID + 0x2A301,// 查询VIP等级礼包领取状态
        MSG_W2F2C_ACK_VIPLEVELGIFT_STATE = MSG_BASE_ID + 0x3A301,

		MSG_C2F2W_REQ_DIVINE_ROULETTE_INFO  = MSG_BASE_ID + 0x2A096,// CLIENT向WORLD请求占卜玩法轮盘物品信息
		MSG_W2F2C_ACK_DIVINE_ROULETTE_INFO  = MSG_BASE_ID + 0x3A096,// CLIENT向WORLD请求占卜玩法轮盘物品信息

		MSG_C2F2W_REQ_DIVINE_USER_DATA  = MSG_BASE_ID + 0x2A097,//CLIENT向WORLD请求角色占卜玩法数据
		MSG_W2F2C_ACK_DIVINE_USER_DATA 	= MSG_BASE_ID + 0x3A097,

		MSG_C2F2W_REQ_PLAY_DIVINE  		= MSG_BASE_ID + 0x2A098,//CLIENT向WORLD请求占卜
		MSG_W2F2C_ACK_PLAY_DIVINE 		= MSG_BASE_ID + 0x3A098,
		MSG_W2F2C_ACK_DICE_NUM			= MSG_BASE_ID + 0x3A099,//返回筛子的点数
		MSG_W2F2C_ACK_BUY_DICE			= MSG_BASE_ID + 0x3A09A,//扣除金币的消息
		MSG_W2F2C_ACK_DIVINE_ERROR		= MSG_BASE_ID + 0x3A09B,//重新打开面板

        MSG_C2F2W_REQ_WELFARE_USER_DATA = MSG_BASE_ID + 0x2A09C,//CLIENT向WORLD请求角色福利玩法数据
        MSG_W2F2C_ACK_WELFARE_USER_DATA = MSG_BASE_ID + 0x3A09C,

        MSG_C2F2W_REQ_GET_SPIRIT = MSG_BASE_ID + 0x2A09D,//CLIENT向WORLD请求领取体力
        MSG_W2F2C_ACK_GET_SPIRIT = MSG_BASE_ID + 0x3A09D,

        MSG_C2F2W_REQ_GET_CASH_COW = MSG_BASE_ID + 0x2A09E,//CLIENT向WORLD请求摇钱树
        MSG_W2F2C_ACK_GET_CASH_COW = MSG_BASE_ID + 0x3A09E,

        MSG_C2F2W_REQ_READ_EXP_INFO = MSG_BASE_ID + 0x2A09F,//CLIENT向WORLD请求角色修行信息( 发送此消息，表示角色已开启了修行功能，第一次从当前时间开始计时 )
        MSG_W2F2C_ACK_READ_EXP_INFO = MSG_BASE_ID + 0x3A09F,

        MSG_C2F2W_REQ_GET_EXP = MSG_BASE_ID + 0x2A0A1,//CLIENT向WORLD请求领取修行经验
        MSG_W2F2C_ACK_GET_EXP = MSG_BASE_ID + 0x3A0A1,
        MSG_W2F2C_ACK_GET_EXTRA_EXP = MSG_BASE_ID + 0x3A305,//显示 tip用的  修行消息

		MSG_C2F2D_REQ_USE_PROPS = MSG_BASE_ID + 0x2630E,//使用道具,暂时只有VIP卡.
		MSG_D2F2C_ACK_USE_PROPS = MSG_BASE_ID + 0x3630E,

		MSG_C2F2D_BUY_TILI = MSG_BASE_ID + 0x2630F,//购买体力.
		MSG_D2F2C_BUY_TILI = MSG_BASE_ID + 0x3630F,

		MSG_C2F2D_REQ_CHAR_GAME_DATA = MSG_BASE_ID + 0x26310,//客户端,请求获取玩家游戏数据协议
		MSG_D2F2C_ACK_CHAR_GAME_DATA = MSG_BASE_ID + 0x36310,

        MSG_C2F2D_REQ_DAILY_TASK_INFO = MSG_BASE_ID + 0x26303,
        MSG_D2F2C_ACK_DAILY_TASK_INFO = MSG_BASE_ID + 0x36303,

        MSG_C2F2D_REQ_DAILY_TASK_AWARD = MSG_BASE_ID + 0x26304,//2.领取任务奖励协议
        MSG_D2F2C_ACK_DAILY_TASK_AWARD = MSG_BASE_ID + 0x36304,

        MSG_C2F2W_REQ_ZHANJIANG_INFO = MSG_BASE_ID + 0x2A0A2,//玩家请求斩将界面信息
        MSG_W2F2C_ACK_ZHANJIANG_INFO = MSG_BASE_ID + 0x3A0A2,

        MSG_C2F2W_REQ_ZHANJIANG_CAN_REFRESH_CHALLENGER = MSG_BASE_ID + 0x2A0A3,//玩家请求能否刷新匹配列表协议
        MSG_W2F2C_ACK_ZHANJIANG_CAN_REFRESH_CHALLENGER = MSG_BASE_ID + 0x3A0A3,

        MSG_C2F2W_REQ_ZHANJIANG_DO_REFRESH_CHALLENGER = MSG_BASE_ID + 0x2A0A4,//玩家请求执行刷新匹配列表协议
        MSG_W2F2C_ACK_ZHANJIANG_DO_REFRESH_CHALLENGER = MSG_BASE_ID + 0x3A0A4,

        MSG_C2F2W_REQ_ZHANJIANG_RECV_AWARD = MSG_BASE_ID + 0x2A0A5,//玩家请求领取挑战奖励协议
        MSG_W2F2C_ACK_ZHANJIANG_RECV_AWARD = MSG_BASE_ID + 0x3A0A5,

        MSG_C2F2D_REQ_BUY_ACTIVITY_FUND = MSG_BASE_ID + 0x26312,//玩家购买基金协议
        MSG_D2F2C_ACK_BUY_ACTIVITY_FUND = MSG_BASE_ID + 0x36312,

        MSG_C2F2W_REQ_ZHANJIANG_CHALLENGE = MSG_BASE_ID + 0x2A0A6,//玩家请求挑战协议
        MSG_W2F2C_ACK_ZHANJIANG_CHALLENGE = MSG_BASE_ID + 0x3A0A6,

		MSG_C2F2B_REQ_ENTER_KILL_GENERALS = MSG_BASE_ID + 0x2816D,//请求,进入斩将.
        MSG_B2F2C_ACK_ENTER_KILL_GENERALS = MSG_BASE_ID + 0x3816D,

		MSG_C2F2B_REQ_ENTER_KILL_GENERALS_REVENGE = MSG_BASE_ID + 0x2816F,//进入斩将复仇.

        MSG_C2F2B_REQ_KILL_GENERALS_RESULT = MSG_BASE_ID + 0x2816E,//发送,战斗结果.
        MSG_B2F2C_ACK_KILL_GENERALS_RESULT = MSG_BASE_ID + 0x3816E,

		MSG_C2F2B_REQ_ENTRY_YABIAO = MSG_BASE_ID + 0x28173,//押镖的4个战斗协议.
		MSG_B2F2C_ACK_ENTRY_YABIAO = MSG_BASE_ID + 0x38173,
		MSG_C2F2B_REQ_YABIAO_RESULT = MSG_BASE_ID + 0x28174,
		MSG_B2F2C_ACK_YABIAO_RESULT = MSG_BASE_ID + 0x38174,

        MSG_D2F2C_PUSH_DAILY_TASK_REFRESH = MSG_BASE_ID + 0x36305,//数据已经被刷新，请重新打开日常任务面板

        MSG_C2F2W_REQ_RECV_FENGLU = MSG_BASE_ID + 0x2A0A8,// 请求俸禄  奖励
        MSG_W2F2C_ACK_RECV_FENGLU = MSG_BASE_ID + 0x3A0A8,// 请求俸禄  得到的 奖励

        MSG_C2F2W_REQ_ZHANJIANG_RANKING_LIST = MSG_BASE_ID + 0x2A0A7,//玩家请求斩将排行榜信息
        MSG_W2F2C_ACK_ZHANJIANG_RANKING_LIST = MSG_BASE_ID + 0x3A0A7,

        MSG_C2F2W_REQ_ZHANJIANG_REVENGE = MSG_BASE_ID + 0x2A0AA,//玩家请求复仇协议
        MSG_W2F2C_ACK_ZHANJIANG_REVENGE = MSG_BASE_ID + 0x3A0AA,

        MSG_C2F2W_REQ_MALL_USER_DATA = MSG_BASE_ID + 0x2A0AB,//CLIENT向WORLD请求角色商城信息
        MSG_W2F2C_ACK_MALL_USER_DATA = MSG_BASE_ID + 0x3A0AB,

        MSG_C2F2W_REQ_BUY_MALL_GOODS = MSG_BASE_ID + 0x2A0AC,//CLIENT向WORLD请求购买商城物品( 订单协议 )
        MSG_W2F2C_ACK_BUY_MALL_GOODS = MSG_BASE_ID + 0x3A0AC,

        MSG_C2F2D_REQ_SELL_GODCARD_TATTER = MSG_BASE_ID + 0x26306,//出售卡碎片
        MSG_D2F2C_ACK_SELL_GODCARD_TATTER = MSG_BASE_ID + 0x36306,

        MSG_C2F2D_REQ_SELL_PROPS = MSG_BASE_ID + 0x26402,//出售道具 材料
        MSG_C2F2D_ACK_SELL_PROPS = MSG_BASE_ID + 0x36402,

        MSG_C2F2D_REQ_INHERIT_EQUIPMENT_BY_INGOT = MSG_BASE_ID + 0x26302,// 装备传承，只能用金币传承
        MSG_D2F2C_ACK_INHERIT_EQUIPMENT_BY_INGOT = MSG_BASE_ID + 0x36302,

        MSG_C2F2W_REQ_SOCIATY_RANK_INFO = MSG_BASE_ID + 0x2A0B7,//请求公会排行信息信息
        MSG_W2F2C_ACK_SOCIATY_RANK_INFO = MSG_BASE_ID + 0x3A0B7,

        MSG_C2F2W_REQ_SOCIATY_NODE_BASE_INFO = MSG_BASE_ID + 0x2A0B9,//请求公会结点基本信息
        MSG_W2F2C_ACK_SOCIATY_NODE_BASE_INFO = MSG_BASE_ID + 0x3A0B9,

        MSG_C2F2W_REQ_CREATE_SOCIATY = MSG_BASE_ID + 0x2A0AD,//玩家请求创建公会.
        MSG_W2F2C_ACK_CREATE_SOCIATY = MSG_BASE_ID + 0x3A0AD,

        MSG_C2F2W_REQ_SOCIATY_PLAYER_NODE_INFO = MSG_BASE_ID + 0x2A0B8,//请求公会角色结点信息返回值
        MSG_W2F2C_ACK_SOCIATY_PLAYER_NODE_INFO = MSG_BASE_ID + 0x3A0B8,

        MSG_C2F2W_REQ_SOCIATY_MEMBER_INDEXS = MSG_BASE_ID + 0x2A0BE,//请求公会成员的索引信息
        MSG_W2F2C_ACK_SOCIATY_MEMBER_INDEXS = MSG_BASE_ID + 0x3A0BE,

        MSG_C2F2W_REQ_SOCIATY_NODE_MEMBER_INFO = MSG_BASE_ID + 0x2A0BA,//请求公会成员信息的返回值
        MSG_W2F2C_ACK_SOCIATY_NODE_MEMBER_INFO = MSG_BASE_ID + 0x3A0BA,

        MSG_C2F2W_REQ_JION_IN_SOCIATY = MSG_BASE_ID + 0x2A0AE,//玩家请求加入公会.
        MSG_W2F2C_ACK_JION_IN_SOCIATY = MSG_BASE_ID + 0x3A0AE,

        MSG_C2F2W_REQ_SOCIATY_APP_INDEXS = MSG_BASE_ID + 0x2A0BF,//请求公会申请表的索引信息
        MSG_W2F2C_REQ_SOCIATY_APP_INDEXS = MSG_BASE_ID + 0x3A0BF,

        MSG_C2F2W_REQ_SOCIATY_APP_INFO = MSG_BASE_ID + 0x2A0BB,//请求公会申请表信息
        MSG_W2F2C_ACK_SOCIATY_APP_INFO = MSG_BASE_ID + 0x3A0BB,

        MSG_C2F2W_REQ_PROCESS_PLAYER_APP = MSG_BASE_ID + 0x2A0AF,//同意或者拒绝玩家的入会申请
        MSG_W2F2C_ACK_PROCESS_PLAYER_INFO = MSG_BASE_ID + 0x3A0AF,

        MSG_C2F2W_REQ_DISSOLUTION_SOCIATY = MSG_BASE_ID + 0x2A0B0,//公会解散协议
        MSG_W2F2C_ACK_DISSOLUTION_SOCIATY = MSG_BASE_ID + 0x3A0B0,

        MSG_C2F2W_REQ_QUITE_SOCIATY = MSG_BASE_ID + 0x2A0B3,//玩家主动退出公会
        MSG_W2F2C_ACK_QUITE_SOCIATY = MSG_BASE_ID + 0x3A0B3,

        MSG_C2F2W_REQ_EXPEL_SOCIATY_MEMBER = MSG_BASE_ID + 0x2A0B2,//开除公会成员协议
        MSG_W2F2C_ACK_EXPEL_SOCIATY_MEMBER = MSG_BASE_ID + 0x3A0B2,

        MSG_C2F2W_REQ_MODIFY_SOCIATY_MEMBER_POS = MSG_BASE_ID + 0x2A0B6,//修改公会成员职位
        MSG_W2F2D_ACK_MODIFY_SOCIATY_MEMBER_POS = MSG_BASE_ID + 0x3A0B6,

        MSG_C2F2W_REQ_TRANSFER_SOCIATY = MSG_BASE_ID + 0x2A0B1,//公会转让协议.
        MSG_W2F2C_ACK_TRANSFER_SOXIATY = MSG_BASE_ID + 0x3A0B1,

        MSG_C2F2W_REQ_MODIFY_SOCIATY_DEC = MSG_BASE_ID + 0x2A0B4,//修改公会宣言
        MSG_W2F2C_ACK_MODIFY_SOCIATY_DEC = MSG_BASE_ID + 0x3A0B4,

        MSG_C2F2W_ERQ_MODIFY_SOCIATY_NAME = MSG_BASE_ID + 0x2A0B5,//请求修改公会名称
        MSG_W2F2C_ACK_MODIFY_SOCIATY_NAME = MSG_BASE_ID + 0x3A0B5,

        MSG_C2F2W_REQ_DELETE_POS = MSG_BASE_ID + 0x2A0A0,//请求解除玩家的职务
        MSG_W2F2C_ACK_DELETE_POS = MSG_BASE_ID + 0x3A0A0,

        MSG_C2F2W_REQ_ZHANJIANG_BUYTIMES = MSG_BASE_ID + 0x2A0BD,//玩家请求购买斩将次数
        MSG_W2F2C_ACK_ZHANJIANG_BUYTIMES = MSG_BASE_ID + 0x3A0BD,

        MSG_C2F2W_REQ_PLAYER_RANK = MSG_BASE_ID + 0x2A313,//查询玩家排行名次
        MSG_W2F2C_ACK_PLAYER_RANK = MSG_BASE_ID + 0x3A313,

        MSG_C2F2W_REQ_SOCIATY_ZU_MA_INFO = MSG_BASE_ID + 0x2A0C2,//请求祖玛信息
        MSG_W2F2C_ACK_SOCIATY_ZU_MA_INFO = MSG_BASE_ID + 0x3A0C2,

        MSG_C2F2W_REQ_SOCIATY_GONG_XIAN = MSG_BASE_ID + 0x2A0C0,//公会捐献
        MSG_W2F2C_ACK_SOCIATY_GONG_XIAN = MSG_BASE_ID + 0x3A0C0,

        MSG_C2F2W_REQ_HUAN_XING_ZU_MA = MSG_BASE_ID + 0x2A0C3,//请求唤醒祖玛
        MSG_W2F2C_ACK_HUAN_XING_ZU_MA = MSG_BASE_ID + 0x3A0C3,

        MSG_C2F2W_REQ_ATT_ZU_MA = MSG_BASE_ID + 0x2A0C4,//请求攻击祖玛
        MSG_W2F2C_ACK_ATT_ZU_MA = MSG_BASE_ID + 0x3A0C4,

        MSG_C2F2W_REQ_UP_SOCIATY_SHANG_DIAN_LV = MSG_BASE_ID + 0x2A0C7,//请求升级公会商店
        NSG_W2F2C_ACK_UP_SSOCIATY_SHANG_DIAN_LV = MSG_BASE_ID + 0x3A0C7,

        MSG_C2F2W_REQ_SOCIATY_UP_LV = MSG_BASE_ID + 0x2A0C1,//公会升级
        MSG_W2F2C_ACK_SOCIATY_UP_LV = MSG_BASE_ID + 0x3A0C1,

        MSG_C2F2D_REQ_REPAIR_EQUIPMENT = MSG_BASE_ID + 0x26078,// 装备修复
        MSG_C2F2D_ACK_REPAIR_EQUIPMENT = MSG_BASE_ID + 0x36078,

        MSG_C2F2W_REQ_MATCH_INDIVIDUAL_ATHLETICS = MSG_BASE_ID + 0x2A31D,// 个人竞技请求匹配
        MSG_W2F2C_ACK_MATCH_INDIVIDUAL_ATHLETICS = MSG_BASE_ID + 0x3A31D,

        MSG_C2F2W_REQ_CANCLE_MATCH_INDIVIDUAL_ATHLETICS = MSG_BASE_ID + 0x2A31E,// 个人竞技取消匹配
        MSG_W2F2C_ACK_CANCLE_MATCH_INDIVIDUAL_ATHLETICS = MSG_BASE_ID + 0x3A31E,

        MSG_W2F2c_PUSH_MATCH_SUCCESS = MSG_BASE_ID + 0x2A31F,//匹配成功push消息

        MSG_C2F2W_REQ_UP_PLAYER_TITLE = MSG_BASE_ID + 0x2A31C,//请求升级个人竞技称号
        MSG_W2F2C_ACK_UP_PLAYER_TITLE = MSG_BASE_ID + 0x3A31C,

        MSG_C2F2W_REQ_PLAYER_INDIVIDUAL_ATHLETICS_INFO = MSG_BASE_ID + 0x2A31B,// 请求玩家个人竞技信息
        MSG_W2F2C_ACK_PLAYER_INDIVIDUAL_ATHLETICS_INFO = MSG_BASE_ID + 0x3A31B,

        MSG_C2F2W_REQ_CREATE_TEAM_PVP = MSG_BASE_ID + 0x2A321,//请求升级个人竞技称号
        MSG_W2F2C_ACK_CREATE_TEAM_PVP = MSG_BASE_ID + 0x3A321,

        MSG_C2F2W_REQ_JOIN_TEAM_PVP = MSG_BASE_ID + 0x2A323,// 服务器返回玩家请求进入队伍，进入队伍的同时返回队伍里已有角色及座位信息
        MSG_W2F2C_ACK_JOIN_TEAM_PVP = MSG_BASE_ID + 0x3A323,

		MSG_C2F2W_REQ_PLAYER_KICK_PLAYER_TEAM_PVP = MSG_BASE_ID + 0x2A325,// 服务器返回玩家踢人
        MSG_C2F2W_ACK_PLAYER_KICK_PLAYER_TEAM_PVP = MSG_BASE_ID + 0x3A325,

        MSG_C2F2W_REQ_PLAYER_EXIT_TEAM_PVP = MSG_BASE_ID + 0x2A326,// 玩家请求退出队伍
		MSG_W2F2C_ACK_PLAYER_EXIT_TEAM_PVP = MSG_BASE_ID + 0x3A326,

        MSG_W2F2C_PUSH_PLAYER_ENTER_TEAM_PVP = MSG_BASE_ID + 0x2A324,// 服务器告诉队伍内的玩家, 有新玩家进入队伍
		
		MSG_W2F2C_PUSH_PLAYER_QUIT_TEAM_PVP = MSG_BASE_ID + 0x3A327,// 服务器告诉队伍内的玩家, 有玩家离开队伍

        MSG_W2F2C_PUSH_KICKEDOUT_TEAM_PVP = MSG_BASE_ID + 0x2A32B,// World服务器向玩家推送被踢出队伍

        MSG_C2F2W_REQ_QUICK_JOIN_TEAM_PVP = MSG_BASE_ID + 0x2A329,// 玩家请求快速进入队伍
        MSG_W2F2C_ACK_QUICK_JOIN_TEAM_PVP = MSG_BASE_ID + 0x3A329,

        MSG_C2F2W_REQ_SOCIATY_TEAM_MATCH = MSG_BASE_ID + 0x2A32C,//玩家请求匹配 公会
        MSG_C2F2W_ACK_SOCIATY_TEAM_MATCH = MSG_BASE_ID + 0x3A32C,

        MSG_C2F2W_REQ_SOCIATY_TEAM_CANCEL_MATCH = MSG_BASE_ID + 0x2A32D,//玩家请求取消匹配 公会
        MSG_W2F2C_ACK_SOCIATY_TEAM_CANCEL_MATCH = MSG_BASE_ID + 0x3A32D,

        MSG_C2F2W_REQ_GONG_HUI_ZHAN_INFO = MSG_BASE_ID + 0x2A32F,//请求玩家的公会对战信息
        MSG_W2F2C_ACK_GONG_HUI_ZHAN_INFO = MSG_BASE_ID + 0x3A32F,

        MSG_C2F2W_REQ_RECV_CAN_ZHAN_JIANG_LI = MSG_BASE_ID + 0x2A330,//玩家请求领取参战礼包
        MSG_W2F2C_ACK_RECV_CAN_ZHAN_JIANG_LI = MSG_BASE_ID + 0x3A330,

        MSG_C2F2W_REQ_SOCIATY_SCORE_RANK_INFO = MSG_BASE_ID + 0x2A331,//请求公会积分排行榜
        MSG_W2F2C_ACK_SOCIATY_SCORE_RANK_INFO = MSG_BASE_ID + 0x3A331,

        MSG_C2F2D_REQ_CIBANG_GROWP_UP = MSG_BASE_ID + 0x26409,//请求进行翅膀培养
        MSG_D2F2C_ACK_CIBANG_GROWP_UP = MSG_BASE_ID + 0x36409,

        MSG_C2F2W_REQ_LOTTERY_AWARD = MSG_BASE_ID + 0x2A334,//客户端请求,抽奖
        MSG_W2F2C_ACK_LOTTERY_AWARD = MSG_BASE_ID + 0x3A334,

        MSG_C2F2D_REQ_CONFIRM_WING_GROWPUP = MSG_BASE_ID + 0x26410,//确认上次培养操作
        MSG_D2F2C_ACK_CONFIRM_WING_GROWPUP = MSG_BASE_ID + 0x36410,

        MSG_C2F2W_ACK_SOCIATY_TEAM_ROOM_INFO = MSG_BASE_ID + 0x3A32E,//push通知队伍成员分配的房间信息 公会

        MSG_C2F2W_REQ_PLAYER_INVITATION_TEAM_PVP = MSG_BASE_ID + 0x2A322,//服务器返回玩家发布邀请，返回NoError，不满足返回错误编号。注意：收到无错误ACK以后客户端必须补发一条MSG_C2F2W_REQ_SEND_COMMUNICATION_INFO消息，用于广播，目前采用这个做法主要是我没找到简便的服务器广播消息函数
        MSG_C2F2W_ACK_PLAYER_INVITATION_TEAM_PVP = MSG_BASE_ID + 0x3A322,

        MSG_C2F2W_REQ_SOCIATY_ZU_MA_SHANG_HAI_RANK_INFO = MSG_BASE_ID + 0x2A0CB,//请求祖玛伤害排行信息
        MSG_W2F2C_ACK_SOCIATY_ZU_MA_SHANG_HAI_RANK_INFO = MSG_BASE_ID + 0x3A0CB,

        MSG_C2F2W_REQ_SOCIATY_FU_LI_INFO = MSG_BASE_ID + 0x2A0CA,//请求公会福利信息
        MSG_W2F2C_ACK_SOCIATY_FU_LI_INFO = MSG_BASE_ID + 0x3A0CA,

        MSG_C2F2W_REQ_SOCIATY_PLAYER_BUY_GOODS_INFO = MSG_BASE_ID + 0x2A0C5,//CLIENT向WORLD请求角色公会商店购买信息
        MSG_W2F2C_ACK_SOCIATY_PLAYER_BUY_GOODS_INFO = MSG_BASE_ID + 0x3A0C5,

        MSG_C2F2W_REQ_BUY_SOCIATY_GOODS = MSG_BASE_ID + 0x2A0C6,//CLIENT向WORLD请求购买公会商品
        MSG_W2F2C_ACK_BUY_SOCIATY_GOODS = MSG_BASE_ID + 0x3A0C6,

        MSG_C2F2W_REQ_RECV_SOCIATY_GONG_XIAN_BAO_XIANG = MSG_BASE_ID + 0x2A0C8,//请求领取每日贡献奖励
        MSG_W2F2C_ACK_RECV_SOCIATY_GONG_XIAN_BAO_XIANG = MSG_BASE_ID + 0x3A0C8,

        MSG_C2F2W_REQ_RECV_SOCIATY_ZU_MA_BAO_XIANG = MSG_BASE_ID + 0x2A0C9,//请求领取祖玛宝箱
        MSG_W2F2C_ACK_RECV_SOCIATY_ZU_MA_BAO_XIANG = MSG_BASE_ID + 0x3A0C9,

        MSG_C2F2D_REQ_ACCOUNT_ACTIVITY_INFO = MSG_BASE_ID + 0x2630B,//客户端,获取活动信息
        MSG_D2F2C_ACK_ACCOUNT_ACTIVITY_INFO = MSG_BASE_ID + 0x3630B,

        MSG_C2F2D_REQ_QUERY_ACTIVITY_OPENINFO = MSG_BASE_ID + 0x2630D,//客户端,查询活动开启情况
        MSG_D2F2C_ACK_QUERY_ACTIVITY_OPENINFO = MSG_BASE_ID + 0x3630D,

        MSG_C2F2D_REQ_RECEIVED_ACTIVITY_AWARD = MSG_BASE_ID + 0x2630C,//客户端,领取活动奖励
        MSG_D2F2C_ACK_RECEIVED_ACTIVITY_AWARD = MSG_BASE_ID + 0x3630C,

        MSG_D2F2C_FUSH_ACTIVITY_DATA = MSG_BASE_ID + 0x36311,//推送完成的活动信息

        //押镖先关 的协议
        MSG_C2F2W_REQ_READ_BANDIT_USER_DATA = MSG_BASE_ID + 0x2A306,//CLIENT向WORLD请求读取角色押镖信息
        MSG_W2F2C_ACK_READ_BANDIT_USER_DATA = MSG_BASE_ID + 0x3A306,

        MSG_C2F2W_REQ_REFRESH_YABIAO_INFO = MSG_BASE_ID + 0x2A307,//CLIENT向WORLD请求刷新正在押镖的镖车信息( 订单协议 )
        MSG_W2F2C_ACK_REFRESH_YABIAO_INFO = MSG_BASE_ID + 0x3A307,

        MSG_C2F2W_REQ_GET_YABIAO_INFO = MSG_BASE_ID + 0x2A308,//CLIENT向WORLD请求查询正在押镖的角色信息
        MSG_W2F2C_ACK_GET_YABIAO_INFO = MSG_BASE_ID + 0x3A308,

        MSG_C2F2W_REQ_REFRESH_BIAOCHE_ID = MSG_BASE_ID + 0x2A309,//CLIENT向WORLD请求刷新角色镖车ID
        MSG_W2F2C_ACK_REFRESH_BIAOCHE_ID = MSG_BASE_ID + 0x3A309,

        MSG_C2F2W_REQ_GET_HELP_COUNT = MSG_BASE_ID + 0x2A30A,//CLIENT向WORLD请求读取公会角色被邀请帮忙压镖的次数
        MSG_W2F2C_ACK_GET_HELP_COUNT = MSG_BASE_ID + 0x3A30A,

        MSG_C2F2W_REQ_YABIAO = MSG_BASE_ID + 0x2A30B,//CLIENT向WORLD请求角色开始押镖
        MSG_W2F2C_ACK_YABIAO = MSG_BASE_ID + 0x3A30B,

        MSG_C2F2W_REQ_YABIAO_AWARD = MSG_BASE_ID + 0x2A30C,////CLIENT向WORLD请求角色押镖奖励信息
        MSG_W2F2C_ACK_YABIAO_AWARD = MSG_BASE_ID + 0x3A30C,

        MSG_C2F2W_REQ_GET_AWARD = MSG_BASE_ID + 0x2A30D,//CLIENT向WORLD请求角色领取奖励( 物品容器 )
        MSG_W2F2C_ACK_GET_AWARD = MSG_BASE_ID + 0x3A30D,

        MSG_C2F2W_REQ_BANDIT_FIGHT_INFO = MSG_BASE_ID + 0x2A30E,//CLIENT向WORLD请求角色领取奖励( 物品容器 )
        MSG_W2F2C_ACK_BANDIT_FIGHT_INFO = MSG_BASE_ID + 0x3A30E,

        MSG_C2F2W_REQ_SEARCH_YABIAO_PLAYER = MSG_BASE_ID + 0x2A30F,//CLIENT向WORLD请求搜索正在押镖的玩家信息( 订单协议 )
        MSG_W2F2C_ACK_SEARCH_YABIAO_PLAYER = MSG_BASE_ID + 0x3A30F,

        MSG_C2F2W_REQ_BUY_JIEBIAO_COUNT = MSG_BASE_ID + 0x2A311,//CLIENT向WORLD请求搜索正在押镖的玩家信息( 订单协议 )
        MSG_W2F2C_ACK_BUY_JIEBIAO_COUNT = MSG_BASE_ID + 0x3A311,

        MSG_C2F2W_REQ_SET_POSITION = MSG_BASE_ID + 0x2A312,//服务器上传我的位置

        MSG_C2F2W_REQ_SHOW_SOCIAYT_RANK_INFO = MSG_BASE_ID + 0x2A0BC,//请求公会排行信息
        MSG_W2F2C_ACK_SHOW_SOCIATY_RANK_INFO = MSG_BASE_ID + 0x3A0BC,//公会排行信息返回
    }


    enum RESULT_FD2C_FEP
    {
        RESULT_FD2C_FEP_OK = 0,	// 成功
        RESULT_FD2C_FEP_SERVER_BUSY = 1,	// 服务器忙，请稍候再试
        RESULT_FD2C_FEP_FULL = 2,	// 所有的FEP都满了，客户端可以稍后再试
        RESULT_FD2C_FEP_INVALID_USERDATA = 3,	// 客户端发送的用户数据不对，客户端需要重新登录
        RESULT_FD2C_FEP_USERDATA_TIMEOUT = 4,	// 客户端发送的用户数据已经过期了，客户端需要重新登录
        RESULT_FD2C_FEP_WRONGVERSION = 5,  	// 版本验证失败
    }

    enum RESULT_D2F2C_LOGIN
    {
        RESULT_D2F2C_LOGIN_OK = 0,   	// 登录成功
        RESULT_D2F2C_LOGIN_SERVER_BUSY = 1,	// 服务器忙，请稍候再试
        RESULT_D2F2C_LOGIN_FULL = 2,   	// 本FEP满了，客户端可以稍后再试
        RESULT_D2F2C_LOGIN_INVALID_USERDATA = 3,	// 客户端发送的用户数据不对，客户端需要重新登录
        RESULT_D2F2C_LOGIN_USERDATA_TIMEOUT = 4,	// 客户端发送的用户数据已经过期了，客户端需要重新登录
        RESULT_D2F2C_LOGIN_ACCOUNT_BANNED = 5,   	// 帐号已被紧闭，暂时不能登录
        RESULT_D2F2C_LOGIN_WRONG_EXECUTION = 6,    // 各种原因的执行异常        
    }
	// 
	// 服务器返回创建角色的结果
	// 
	enum RESULT_D2F2C_CREATE_CHARACTER
	{
		RESULT_D2F2C_CREATE_CHARACTER_OK          = 0 ,	// 成功
		RESULT_D2F2C_CREATE_CHARACTER_SERVER_BUSY = 1 ,	// 服务器忙
		RESULT_D2F2C_CREATE_CHARACTER_SAME_NAME   = 2 ,	// 已经有同名的角色
		RESULT_D2F2C_CREATE_CHARACTER_FULL        = 3 ,	// 该帐号已经不能再创建新的角色了
		RESULT_D2F2C_CREATE_CHARACTER_ILLEGAL     = 4 , // 发送的新角色信息不合法
		RESULT_D2F2C_CREATE_CHARACTER_NO_ACCOUNT  = 5 ,	// 没有这个帐号的玩家（或者这个帐号的玩家当前处在禁闭中）
	}
	// 
	// 服务器返回选择角色的结果
	// 
	enum RESULT_D2F2C_SELECT_CHARACTER
	{
		RESULT_D2F2C_SELECT_CHARACTER_OK          = 0 ,	// 成功
		RESULT_D2F2C_SELECT_CHARACTER_SERVER_BUSY = 1 ,	// 服务器忙
		RESULT_D2F2C_SELECT_CHARACTER_IN_USE      = 2 ,	// 这个角色当前正在使用
		RESULT_D2F2C_SELECT_CHARACTER_ILLEGAL     = 3 ,	// 选择的角色ID不合法（比如不是该玩家的角色）
		RESULT_D2F2C_SELECT_CHARACTER_BANNED      = 4 ,	// 所选角色当前处在禁闭期中
		RESULT_D2F2C_SELECT_CHARACTER_NO_ACCOUNT  = 5 ,	// 没有这个帐号的玩家（或者这个帐号的玩家当前处在禁闭中）
	}
	
	// 
	// 服务器返回删除角色的结果
	// 
	enum RESULT_D2F2C_DELETE_CHARACTER
	{
		RESULT_D2F2C_DELETE_CHARACTER_OK             = 0 ,	// 成功
		RESULT_D2F2C_DELETE_CHARACTER_SERVER_BUSY    = 1 ,	// 服务器忙
		RESULT_D2F2C_DELETE_CHARACTER_IN_USE         = 2 ,	// 这个角色当前正在使用，不能删除这个角色
		RESULT_D2F2C_DELETE_CHARACTER_UNION_CHAIRMAN = 3 ,	// 这个人是门派的帮主，不能删除这个角色
		RESULT_D2F2C_DELETE_CHARACTER_MARRIAGE       = 4 ,	// 这个人当前有婚姻关系，不能删除这个角色
		RESULT_D2F2C_DELETE_CHARACTER_ILLEGAL        = 5 ,	// 所要删除的角色ID不合法（比如不是该玩家的角色）
		RESULT_D2F2C_DELETE_CHARACTER_NO_ACCOUNT     = 6 ,	// 没有这个帐号的玩家（或者这个帐号的玩家当前处在禁闭中）
	}
}